name: VoiceFlowApp
options:
  bundleIdPrefix: com.voiceflow
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  VoiceFlowApp:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.voiceflow.app
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/VoiceFlowApp.entitlements
        ENABLE_HARDENED_RUNTIME: NO
        CODE_SIGN_IDENTITY: "-"
        PRODUCT_NAME: VoiceFlow
    entitlements:
      path: Resources/VoiceFlowApp.entitlements
